import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {RealtimeClient,type VoiceEvent} from './realtime';
let track:{enabled:boolean;stop:ReturnType<typeof vi.fn>},events:VoiceEvent[],streamController:ReadableStreamDefaultController<Uint8Array>,calls:Array<{url:string;body:Record<string,unknown>}>;
const media=()=>({getTracks:()=>[track],getAudioTracks:()=>[track]});
class Peer {static instances:Peer[]=[];connectionState='new';ontrack:unknown;onconnectionstatechange:unknown;close=vi.fn();addTrack=vi.fn();createDataChannel=vi.fn();constructor(){Peer.instances.push(this);}async createOffer(){return{sdp:'v=0 mock offer'};}async setLocalDescription(){}async setRemoteDescription(){}}
class AudioMock {autoplay=false;srcObject=null;play=vi.fn(async()=>{});pause=vi.fn();}
const emit=(e:VoiceEvent)=>streamController.enqueue(new TextEncoder().encode(`data: ${JSON.stringify({sessionId:'owned',generation:0,seq:events.length+1,...e})}\n\n`));
beforeEach(()=>{track={enabled:true,stop:vi.fn()};events=[];calls=[];Peer.instances=[];vi.stubGlobal('navigator',{mediaDevices:{getUserMedia:vi.fn(async()=>media())}});vi.stubGlobal('RTCPeerConnection',Peer);vi.stubGlobal('Audio',AudioMock);vi.stubGlobal('fetch',vi.fn(async(url:string,init:RequestInit={})=>{calls.push({url,body:init.body?JSON.parse(String(init.body)): {}});if(url.endsWith('/start'))return Response.json({ok:true,data:{sessionId:'owned',sdp:'v=0 mock answer'}});if(url.endsWith('/events'))return new Response(new ReadableStream({start(c){streamController=c;}}));return Response.json({ok:true});}));});
afterEach(()=>vi.unstubAllGlobals());
describe('mocked WebRTC capture ownership (no provider)',()=>{
  it('selects exact device, waits for ready, mutes and releases all resources on end',async()=>{const client=new RealtimeClient(e=>events.push(e));await client.start('laptop');expect(navigator.mediaDevices.getUserMedia).toHaveBeenCalledWith(expect.objectContaining({audio:expect.objectContaining({deviceId:{exact:'laptop'}})}));expect(track.enabled).toBe(false);emit({type:'status',status:'ready'});await vi.waitFor(()=>expect(track.enabled).toBe(true));client.mute(true);expect(track.enabled).toBe(false);await client.end();expect(track.stop).toHaveBeenCalledTimes(1);expect(Peer.instances[0].close).toHaveBeenCalledOnce();expect(calls.at(-1)?.body).toEqual({sessionId:'owned',command:'end'});});
  it('releases late permission grant after navigation without starting a server call',async()=>{let resolve:(value:MediaStream)=>void=()=>{};vi.mocked(navigator.mediaDevices.getUserMedia).mockImplementation(()=>new Promise(r=>{resolve=r;}));const client=new RealtimeClient(e=>events.push(e));const starting=client.start();await client.end('navigation');resolve(media() as unknown as MediaStream);await starting;expect(track.stop).toHaveBeenCalledOnce();expect(calls).toHaveLength(0);});
  it('permission rejection leaves text usable and starts no provider session',async()=>{vi.mocked(navigator.mediaDevices.getUserMedia).mockRejectedValue(new Error('denied'));const client=new RealtimeClient(e=>events.push(e));await client.start();expect(events.at(-1)?.type).toBe('ended');expect(calls).toHaveLength(0);});
  it('drops duplicate and late generations before audio-first delivery',async()=>{const client=new RealtimeClient(e=>events.push(e));await client.start();emit({type:'status',status:'ready',seq:1});emit({type:'status',status:'interrupted',generation:2,seq:2});emit({type:'user',text:'stale',generation:1,seq:3});emit({type:'user',text:'fresh',generation:2,seq:4});emit({type:'user',text:'duplicate',generation:2,seq:4});await vi.waitFor(()=>expect(events.some(e=>e.text==='fresh')).toBe(true));expect(events.some(e=>['stale','duplicate'].includes(e.text??''))).toBe(false);await client.end();});
  it('a rapid push-to-talk press/release cannot leave capture enabled',async()=>{const client=new RealtimeClient(e=>events.push(e));await client.start('',true);emit({type:'status',status:'ready'});await vi.waitFor(()=>expect(events.some(e=>e.status==='ready')).toBe(true));await Promise.all([client.press(),client.release()]);expect(track.enabled).toBe(false);expect(calls.filter(c=>c.url.endsWith('/control')).map(c=>c.body.command)).toEqual(['ptt_start','ptt_end']);await client.end();});
  it('typed turn goes through authenticated application control, not provider data channel',async()=>{const client=new RealtimeClient(e=>events.push(e));await client.start();await client.text('Correction: savings are 18000.');expect(calls.at(-1)?.body).toEqual({sessionId:'owned',command:'text',text:'Correction: savings are 18000.'});await client.end();});
});
