import type {Lang,ScenarioSnapshot} from '@fintwin/contracts';
export const scenarioLabels:Record<string,[string,string]>={
  principal:['Restschuld','Mortgage balance'],rate_pct:['Zins (% p. a.)','Annual interest (%)'],months:['Restlaufzeit (Monate)','Remaining term (months)'],special_repayment_monthly:['Zusätzliche Tilgung / Monat','Extra repayment / month'],age:['Alter','Age'],retirement_age:['Wunsch-Rentenalter','Retirement age'],current_assets:['Anlagen und Altersvorsorge','Investments and retirement accounts'],monthly_contribution:['Sparrate / Monat','Monthly contribution'],pension_monthly:['Rente / Monat, heutige Euro','Monthly pension, today’s euros'],spending_monthly:['Wunschbudget, heutige Euro','Target spending, today’s euros'],annual_return_pct:['Rendite (% p. a.)','Annual return (%)'],annual_fee_pct:['Kosten (% p. a.)','Annual fees (%)'],inflation_pct:['Inflation (% p. a.)','Annual inflation (%)'],withdrawal_rate_pct:['Entnahme (% p. a.)','Annual withdrawal (%)'],target_amount:['Zielbetrag','Target amount'],start:['Guthaben + Anlagen','Cash + investments'],monthly:['Sparrate / Monat','Monthly contribution'],baseline_payment:['Bisherige Monatsrate','Current monthly payment'],baseline_principal:['Bisherige Restschuld','Baseline balance'],baseline_rate_pct:['Bisheriger Zins','Baseline rate'],baseline_months:['Bisherige Restlaufzeit','Baseline term'],extra_frequency:['Tilgungsintervall','Extra repayment frequency'],as_of:['Stichtag','As of'],payment:['Monatsrate (ohne Zusatztilgung)','Monthly payment (before extra)'],specialRepayment:['Zusatztilgung / Monat','Monthly extra repayment'],totalInterest:['Zinsen über Laufzeit','Interest over the term'],payoffMonths:['Monate bis Rückzahlung','Months to payoff'],projectedReal:['Projiziertes Kapital (heutige Euro)','Projected capital (today’s euros)'],requiredCapital:['Modellhafter Kapitalbedarf','Modeled capital needed'],sustainableMonthlyReal:['Modellhafte monatliche Entnahme','Modeled monthly withdrawal'],target:['Zielbetrag','Target amount'],reachedYearMonth:['Zielzeitpunkt','Target date'],interest:['Änderung der Zinskosten','Change in interest'],projected_real:['Änderung in heutiger Kaufkraft','Change in today’s purchasing power'],sustainable_monthly:['Änderung monatlicher Entnahme','Change in monthly withdrawal'],extra_interest_saved:['Zinsersparnis nur durch Zusatztilgung','Interest saved by extra repayment'],extra_months_saved:['Verkürzung durch Zusatztilgung','Months saved by extra repayment'],remaining_after_saving:['Danach noch ungebunden / Monat','Remaining unallocated / month'],
};
const assumptions:Record<string,[string,string]>={
  monthly_extra_not_contract_permission:['Monatliche Zusatztilgung als Modellannahme; vertragliche Zulässigkeit offen.','Monthly extra repayment is a model assumption; contract permission is not established.'],spending_includes_housing:['Wohnkosten sind in den Ausgaben enthalten. Die Rate wird nicht doppelt abgezogen.','Housing is included in spending. The mortgage is not deducted twice.'],no_tax_fees_refinancing_costs:['Ohne Steuern, Gebühren und Umschuldungskosten.','Excludes taxes, fees and refinancing costs.'],rounded_monthly_interest:['Zinsen und Tilgung monatlich auf Cent gerundet.','Interest and repayment rounded monthly to cents.'],today_money_pension_and_spending:['Rente und Wunschbudget in heutiger Kaufkraft.','Pension and target spending are in today’s purchasing power.'],fixed_nominal_month_end_contributions:['Gleichbleibende nominale Beiträge zum Monatsende.','Fixed nominal contributions at each month end.'],nominal_return_less_fees_then_inflation:['Nominale Rendite abzüglich Kosten; anschließend Inflationsbereinigung.','Nominal return less fees, then adjusted for inflation.'],withdrawal_ratio_not_probability:['Der Deckungsgrad ist ein Modellverhältnis, keine Erfolgswahrscheinlichkeit.','The readiness ratio is a model ratio, not a probability of success.'],no_tax_or_pension_indexation:['Ohne Steuern und automatische Rentenanpassung.','Excludes tax and pension indexation.'],pension_unknown_no_readiness:['Rente unbekannt: kein persönlicher Deckungsgrad berechenbar.','Pension unknown: no personal readiness ratio can be calculated.'],explicit_zero_pension_scenario_not_fact:['Bewusstes Null-Renten-Szenario; keine persönliche Angabe.','Explicit zero-pension scenario, not a personal fact.'],cash_plus_investments_not_total_net_worth:['Nur Guthaben und Anlagen; Immobilie und Schulden sind nicht enthalten.','Cash and investments only; excludes property and debts.'],nominal_monthly_compounding_end_contributions:['Nominale monatliche Verzinsung; Beiträge am Monatsende.','Nominal monthly compounding; contributions at month end.'],no_tax_fees_or_inflation:['Ohne Steuern, Gebühren und Inflationsausgleich.','Excludes taxes, fees and inflation.'],
};
export const scenarioLabel=(key:string,lang:Lang)=>key==='Δ payment'?(lang==='de'?'Monatsbelastung inkl. Zusatztilgung':'Monthly payment including extra'):(scenarioLabels[key.replace(/^Δ /,'')]??[key,key])[lang==='de'?0:1];
export const assumptionLabel=(key:string,lang:Lang)=>(assumptions[key]??[key,key])[lang==='de'?0:1];
export const scenarioName=(kind:ScenarioSnapshot['kind'],lang:Lang)=>({mortgage:['Immobilienfinanzierung','Mortgage'],retirement:['Ruhestand','Retirement'],goal:['Vermögensziel','Savings goal']}[kind][lang==='de'?0:1]);
