const SHARED_DEMO_CONTEXT = {
  household: "Shared synthetic demo household feed",
  as_of: "2026-08-30T10:00:00+02:00",
  data_boundary: "Banking, brokerage, property and liability records are fictional and identical for every FinTwin demo account. The signed-in person's name, declared net worth, expectations and conversation history are private to that account.",
  financial_snapshot: { net_household_income_monthly_eur: 7240, external_outflows_august_eur: 6672, free_cashflow_august_eur: 568, emergency_runway_months: 7.8, transaction_count: 7666, history_months: 60, source_ids: ["agg_cashflow_202608", "transfer_matches_202608", "shared_demo_ledger"] },
  recurring_costs: { items: [{ name: "Mortgage payment", monthly_eur: 1420 }, { name: "Health insurance", monthly_eur: 612 }, { name: "Education support", monthly_eur: 520 }], year_over_year_change_monthly_eur: 134, source_ids: ["agg_recurring_yoy_202608"] },
  review_topics: { items: ["Fixed mortgage period ends on 31 October 2027", "Recurring costs rose by 134 euros per month", "Income protection is not confirmed in the demo data", "Confirmed net pension income is missing"], source_ids: ["finding_mortgage_refix", "finding_recurring_cost_drift", "finding_protection_data_incomplete", "fact_goal_retirement"] },
  mortgage_sensitivity: { principal_eur: 240000, remaining_months: 240, monthly_payment_eur: { "4_percent": 1454.35, "5_percent": 1583.89, "6_percent": 1719.43 }, source_ids: ["scenario_mortgage_4", "scenario_mortgage_5", "scenario_mortgage_6", "fact_mortgage_balance"] },
  retirement_baseline: { target_age: 63, projected_real_assets_eur: 299810.07, required_capital_eur: 325714, readiness_ratio: 0.92, source_ids: ["scenario_retirement_age63", "fact_retirement_assets", "fact_goal_retirement"] },
};

const HOLDINGS = [
  { symbol: "AAPL", name: "Apple", quantity: 90, currency: "USD", costBasisEur: 14718, sector: "Technology", account: "Demo brokerage" },
  { symbol: "MSFT", name: "Microsoft", quantity: 60, currency: "USD", costBasisEur: 17558, sector: "Technology", account: "Demo brokerage" },
  { symbol: "NVDA", name: "NVIDIA", quantity: 120, currency: "USD", costBasisEur: 9812, sector: "Technology", account: "Demo brokerage" },
  { symbol: "VWCE.DE", name: "Vanguard FTSE All-World ETF", quantity: 300, currency: "EUR", costBasisEur: 33000, sector: "Global equity ETF", account: "Demo brokerage" },
  { symbol: "SAP.DE", name: "SAP", quantity: 100, currency: "EUR", costBasisEur: 15000, sector: "Technology", account: "Demo brokerage" },
  { symbol: "VOW3.DE", name: "Volkswagen preference", quantity: 80, currency: "EUR", costBasisEur: 9200, sector: "Automotive", account: "Demo brokerage" },
];
const FALLBACK_QUOTES = {
  AAPL: { price: 316.85, currency: "USD", oneYearChangePct: 38.4 }, MSFT: { price: 507.29, currency: "USD", oneYearChangePct: 1.3 },
  NVDA: { price: 220.78, currency: "USD", oneYearChangePct: 29.4 }, "VWCE.DE": { price: 166.66, currency: "EUR", oneYearChangePct: 22.7 },
  "SAP.DE": { price: 190.9, currency: "EUR", oneYearChangePct: -17 }, "VOW3.DE": { price: 77.68, currency: "EUR", oneYearChangePct: -17.1 },
  "EURUSD=X": { price: 1.1618, currency: "USD", oneYearChangePct: 0 },
};
const PORTFOLIO_ACTIVITY = [
  ["2022-03-18", "VWCE.DE", 80, 101.25], ["2022-10-11", "AAPL", 30, 142.8], ["2023-02-07", "MSFT", 20, 258.4], ["2023-06-22", "NVDA", 40, 43.6],
  ["2023-11-15", "SAP.DE", 40, 132.2], ["2024-04-09", "VWCE.DE", 90, 117.9], ["2024-08-28", "AAPL", 25, 194.1], ["2024-12-06", "VOW3.DE", 40, 91.5],
  ["2025-03-20", "MSFT", 20, 386.4], ["2025-07-14", "NVDA", 30, 123.1], ["2025-11-05", "SAP.DE", 60, 161.9], ["2026-01-19", "VOW3.DE", 40, 78.5],
  ["2026-03-17", "VWCE.DE", 130, 139.2], ["2026-05-12", "AAPL", 35, 205.7], ["2026-06-25", "MSFT", 20, 475.2], ["2026-07-16", "NVDA", 50, 174.6],
].map(([date, symbol, quantity, price]) => ({ date, symbol, action: "Buy", quantity, price }));
const HISTORY_BASE = [["2025-09",106400],["2025-10",109850],["2025-11",116920],["2025-12",118140],["2026-01",119760],["2026-02",123880],["2026-03",129420],["2026-04",126730],["2026-05",133960],["2026-06",139520],["2026-07",144870],["2026-08",148851]];

const CREATE_PROFILES_SQL = `CREATE TABLE IF NOT EXISTS user_profiles (user_id TEXT PRIMARY KEY,email TEXT,name TEXT NOT NULL,net_worth_eur REAL NOT NULL,expectations TEXT NOT NULL,bank_connected INTEGER NOT NULL DEFAULT 1,preferred_language TEXT NOT NULL DEFAULT 'de',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`;
const CREATE_TURNS_SQL = `CREATE TABLE IF NOT EXISTS conversation_turns (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,role TEXT NOT NULL,content TEXT NOT NULL,source_ids TEXT NOT NULL DEFAULT '[]',mode TEXT NOT NULL DEFAULT 'text',created_at TEXT NOT NULL)`;
const BLOCKED = ["bestes produkt", "für mich kaufen", "trade ausführen", "steuerlich verbindlich", "kredit genehmigen", "best investment", "buy for me", "execute a trade", "guaranteed return"];
let databaseReady;
const quoteCache = new Map();

function json(data, status = 200) { return new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" } }); }
function viewerFromRequest(request) {
  const userId = request.headers.get("oai-authenticated-user-id"); const email = request.headers.get("oai-authenticated-user-email") || ""; let fullName = "";
  const encodedName = request.headers.get("oai-authenticated-user-full-name");
  if (encodedName && request.headers.get("oai-authenticated-user-full-name-encoding") === "percent-encoded-utf-8") try { fullName = decodeURIComponent(encodedName); } catch { fullName = ""; }
  return userId ? { userId, email, fullName } : null;
}
async function ensureDatabase(env) {
  if (!env.DB) throw new Error("Persistent account storage is unavailable.");
  if (!databaseReady) databaseReady = env.DB.batch([env.DB.prepare(CREATE_PROFILES_SQL), env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_user_profiles_updated_at ON user_profiles(updated_at)"), env.DB.prepare(CREATE_TURNS_SQL), env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_conversation_turns_user_created ON conversation_turns(user_id, created_at)")]).then(() => env.DB.prepare("PRAGMA optimize").run());
  await databaseReady;
}
function profileFromRow(row) { return row ? { name: row.name, email: row.email || undefined, netWorth: Number(row.net_worth_eur), expectations: row.expectations, bankConnected: Boolean(row.bank_connected), language: row.preferred_language === "en" ? "en" : "de" } : null; }
async function readProfile(env, userId) { await ensureDatabase(env); return profileFromRow(await env.DB.prepare("SELECT email, name, net_worth_eur, expectations, bank_connected, preferred_language FROM user_profiles WHERE user_id = ?").bind(userId).first()); }
function validatedFullProfile(body, viewer) {
  const name = String(body.name || "").trim().slice(0, 80); const netWorth = Number(body.netWorth); const expectations = String(body.expectations || "").trim().slice(0, 500);
  if (name.length < 2) throw new Error("Please enter your name."); if (!Number.isFinite(netWorth) || Math.abs(netWorth) > 1e12) throw new Error("Please enter a valid net worth.");
  if (expectations.length < 5) throw new Error("Please describe what you expect from FinTwin."); if (body.bankConnected !== true) throw new Error("Connect the shared demo bank to continue.");
  return { name, email: viewer.email, netWorth, expectations, bankConnected: true, language: body.language === "en" ? "en" : "de" };
}
async function saveFullProfile(env, viewer, profile) {
  await ensureDatabase(env); const now = new Date().toISOString();
  await env.DB.prepare(`INSERT INTO user_profiles (user_id,email,name,net_worth_eur,expectations,bank_connected,preferred_language,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET email=excluded.email,name=excluded.name,net_worth_eur=excluded.net_worth_eur,expectations=excluded.expectations,bank_connected=excluded.bank_connected,preferred_language=excluded.preferred_language,updated_at=excluded.updated_at`).bind(viewer.userId, profile.email || null, profile.name, profile.netWorth, profile.expectations, 1, profile.language, now, now).run(); return profile;
}
async function patchProfile(env, viewer, body) {
  const current = await readProfile(env, viewer.userId); if (!current) return null; const next = { ...current };
  if (body.name !== undefined) { const value = String(body.name).trim().slice(0,80); if (value.length < 2) throw new Error("Please enter your name."); next.name = value; }
  if (body.netWorth !== undefined) { const value = Number(body.netWorth); if (!Number.isFinite(value) || Math.abs(value) > 1e12) throw new Error("Please enter a valid net worth."); next.netWorth = value; }
  if (body.expectations !== undefined) { const value = String(body.expectations).trim().slice(0,500); if (value.length < 5) throw new Error("Please describe what you expect from FinTwin."); next.expectations = value; }
  if (body.language !== undefined) next.language = body.language === "en" ? "en" : "de"; next.email = viewer.email || current.email; return saveFullProfile(env, viewer, next);
}
async function loadConversation(env, userId, limit = 20) {
  await ensureDatabase(env); const query = await env.DB.prepare(`SELECT role,content,source_ids,mode,created_at FROM (SELECT role,content,source_ids,mode,created_at FROM conversation_turns WHERE user_id=? ORDER BY created_at DESC LIMIT ?) ORDER BY created_at ASC`).bind(userId, limit).all();
  return (query.results || []).map(row => { let sources = []; try { sources = JSON.parse(row.source_ids || "[]"); } catch {} return { role: row.role, text: row.content, sources, mode: row.mode, createdAt: row.created_at }; });
}
async function saveTurn(env, userId, role, content, sourceIds = [], mode = "text") { await ensureDatabase(env); await env.DB.prepare("INSERT INTO conversation_turns (id,user_id,role,content,source_ids,mode,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(), userId, role, String(content).slice(0,12000), JSON.stringify(sourceIds), mode, new Date().toISOString()).run(); }

async function fetchQuote(symbol) {
  const cached = quoteCache.get(symbol); if (cached && Date.now() - cached.cachedAt < 300000) return cached.value;
  const fallback = { ...FALLBACK_QUOTES[symbol], symbol, source: "snapshot", asOf: "2026-08-31T20:00:00Z" };
  try {
    const response = await fetch(`https://query2.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=1y&interval=1d`, { headers: { "user-agent": "Mozilla/5.0 (compatible; FinTwin/1.0)", accept: "application/json" } });
    if (!response.ok) throw new Error(); const payload = await response.json(); const result = payload.chart?.result?.[0]; const closes = (result?.indicators?.quote?.[0]?.close || []).filter(Number.isFinite); const price = Number(result?.meta?.regularMarketPrice ?? closes.at(-1)); if (!Number.isFinite(price)) throw new Error();
    const first = closes[0] || price; const value = { symbol, price, currency: result.meta?.currency || fallback.currency, oneYearChangePct: first ? (price / first - 1) * 100 : 0, source: "market", asOf: new Date((result.meta?.regularMarketTime || Date.now()/1000)*1000).toISOString() }; quoteCache.set(symbol,{value,cachedAt:Date.now()}); return value;
  } catch { quoteCache.set(symbol,{value:fallback,cachedAt:Date.now()}); return fallback; }
}
async function portfolioContext(profile) {
  const [fxQuote,...quotes] = await Promise.all([fetchQuote("EURUSD=X"),...HOLDINGS.map(item => fetchQuote(item.symbol))]); const eurUsd = Number(fxQuote.price) || 1.1618;
  const holdings = HOLDINGS.map((holding,index) => { const quote=quotes[index]; const priceEur=holding.currency==="USD"?quote.price/eurUsd:quote.price; const valueEur=priceEur*holding.quantity; return {...holding,price:quote.price,priceEur,valueEur,gainEur:valueEur-holding.costBasisEur,gainPct:(valueEur/holding.costBasisEur-1)*100,oneYearChangePct:quote.oneYearChangePct,quoteSource:quote.source,quoteAsOf:quote.asOf,source_ids:[`market_${holding.symbol.replace(/[^a-z0-9]/gi,"_").toLowerCase()}`,`holding_${holding.symbol.replace(/[^a-z0-9]/gi,"_").toLowerCase()}`]}; });
  const marketValueEur=holdings.reduce((s,i)=>s+i.valueEur,0),costBasisEur=holdings.reduce((s,i)=>s+i.costBasisEur,0); holdings.forEach(item=>{item.weightPct=marketValueEur?item.valueEur/marketValueEur*100:0;});
  const sectors=new Map(); holdings.forEach(i=>sectors.set(i.sector,(sectors.get(i.sector)||0)+i.valueEur)); const sectorAllocation=[...sectors].map(([name,valueEur])=>({name,valueEur,weightPct:valueEur/marketValueEur*100})).sort((a,b)=>b.valueEur-a.valueEur);
  const scale=marketValueEur/HISTORY_BASE.at(-1)[1]; const history=HISTORY_BASE.map(([month,value])=>({month,valueEur:Math.round(value*scale)}));
  const assets=[{id:"savings_emergency",type:"savings",name:"Emergency savings",institution:"Demo Bank",valueEur:39100,liquidity:"instant",source_ids:["account_savings_emergency"]},{id:"savings_fixed",type:"savings",name:"Term deposit",institution:"Demo Bank",valueEur:22800,liquidity:"fixed term",source_ids:["account_savings_fixed"]},{id:"retirement_pension",type:"retirement",name:"Private retirement account",institution:"Demo Pension",valueEur:96600,liquidity:"retirement",source_ids:["account_retirement"]},{id:"property_munich",type:"property",name:"Munich family home",valueEur:420000,valuationDate:"2026-07-31",source_ids:["property_valuation_202607"]},{id:"brokerage",type:"investments",name:"Demo brokerage",valueEur:marketValueEur,source_ids:["portfolio_live_value"]}];
  const liabilities=[{id:"mortgage_home",type:"mortgage",name:"Home mortgage",valueEur:240000,fixedUntil:"2027-10-31",ratePct:2.15,source_ids:["fact_mortgage_balance"]}]; const totalAssetsEur=assets.reduce((s,i)=>s+i.valueEur,0),totalLiabilitiesEur=liabilities.reduce((s,i)=>s+i.valueEur,0),modeledNetWorthEur=totalAssetsEur-totalLiabilitiesEur;
  const topThreeWeightPct=holdings.slice().sort((a,b)=>b.valueEur-a.valueEur).slice(0,3).reduce((s,i)=>s+i.weightPct,0);
  return { connection:{name:"FinTwin Demo Brokerage",status:"connected",accountEnding:"4821",mode:"shared synthetic holdings"},asOf:quotes.reduce((latest,item)=>item.asOf>latest?item.asOf:latest,""),pricing:{status:"delayed reference prices",provider:"Yahoo Finance public chart feed with snapshot fallback",eurUsd,containsFallback:quotes.some(i=>i.source==="snapshot")},summary:{marketValueEur,costBasisEur,gainEur:marketValueEur-costBasisEur,gainPct:(marketValueEur/costBasisEur-1)*100,oneYearChangePct:(marketValueEur/history[0].valueEur-1)*100,topThreeWeightPct},holdings,sectorAllocation,history,activity:PORTFOLIO_ACTIVITY,balanceSheet:{assets,liabilities,totalAssetsEur,totalLiabilitiesEur,modeledNetWorthEur,declaredNetWorthEur:Number(profile?.netWorth??487320),reconciliationDifferenceEur:Number(profile?.netWorth??487320)-modeledNetWorthEur},source_ids:["portfolio_live_value","shared_demo_brokerage","portfolio_activity_history","household_balance_sheet"]};
}

function monthsToGoal(start,contribution,annualReturn,target,growStartingBalance){if(start>=target)return 0;const monthlyRate=annualReturn/12;let months=0,invested=growStartingBalance?start:0;const fixed=growStartingBalance?0:start;while(fixed+invested<target&&months<2400){invested=invested*(1+monthlyRate)+contribution;months++;}return months;}
function goalDate(months){const date=new Date("2026-08-30T12:00:00Z");date.setUTCMonth(date.getUTCMonth()+months);return{months,approximate_year:date.getUTCFullYear(),approximate_date:date.toISOString().slice(0,7)};}
async function householdContext(profile){const netWorth=Number(profile?.netWorth??487320),contribution=568;return{signed_in_profile:{name:profile?.name||"FinTwin user",declared_net_worth_eur:netWorth,expectations:profile?.expectations||"Understand the household's finances",source_ids:["account_profile","account_net_worth"]},...SHARED_DEMO_CONTEXT,portfolio_and_balance_sheet:await portfolioContext(profile),million_euro_goal:{target_eur:1e6,monthly_contribution_eur:contribution,assumed_annual_return:.04,if_current_net_worth_also_compounds:goalDate(monthsToGoal(netWorth,contribution,.04,1e6,true)),if_only_new_contributions_compound:goalDate(monthsToGoal(netWorth,contribution,.04,1e6,false)),explanation:"These are two different assumptions. Do not present a single date without making the assumption clear.",source_ids:["account_net_worth","agg_cashflow_202608","goal_projection_4pct"]}};}
function sourceIds(value,found=new Set()){if(!value||typeof value!=="object")return[...found];if(Array.isArray(value))value.forEach(i=>sourceIds(i,found));else{if(Array.isArray(value.source_ids))value.source_ids.forEach(id=>found.add(id));Object.values(value).forEach(i=>sourceIds(i,found));}return[...found];}
async function groq(path,env,init){if(!env.GROQ_API_KEY)throw new Error("GROQ_API_KEY is unavailable.");const headers=new Headers(init.headers||{});headers.set("authorization",`Bearer ${env.GROQ_API_KEY}`);const response=await fetch(`https://api.groq.com/openai/v1${path}`,{...init,headers});if(!response.ok)throw new Error(`Groq API ${response.status}`);return response;}
function humanize(text){return text.replace(/\*\*/g,"").replace(/`/g,"").replace(/^#{1,6}\s+/gm,"").replace(/^\s*[-•]\s+/gm,"").replace(/^(Model calculations|Modellrechnungen|Modellrechnung)\s*[-:]\s*/i,"").replace(/\n{3,}/g,"\n\n").trim();}

async function answerQuestion(question,env,language="de",profile,conversation=[]){
  const lower=question.toLocaleLowerCase(language==="de"?"de":"en");if(BLOCKED.some(term=>lower.includes(term)))return{display_response:language==="en"?"I can’t choose or trade a financial product for you. I can still show where your portfolio is concentrated, explain diversification trade-offs, and help you prepare questions for a qualified adviser.":"Ich kann kein Finanzprodukt für Sie auswählen oder handeln. Ich kann aber zeigen, wo Ihr Depot konzentriert ist, Diversifikationsabwägungen erklären und Fragen für eine qualifizierte Beratung vorbereiten.",claims:[],policy_result:"blocked",mode:"policy_guard",warnings:[language==="en"?"Regulated recommendation restricted.":"Regulierte Empfehlung begrenzt."]};
  const context=await householdContext(profile);
  const system=language==="en"?`You are FinTwin, a warm, perceptive English-speaking financial coach in an ongoing private conversation. Sound like a capable human, never a report. Begin with the answer the person actually needs. Use two or three short natural paragraphs, no headings, bullets, markdown, raw formulas or canned disclaimers. Remember the recent conversation. You have verified context covering their declared profile, complete synthetic household balance sheet, savings, retirement, property, mortgage, holdings, acquisition history, delayed market prices and concentration metrics. Clearly separate declared values, fictional records and delayed prices. You may explain diversification, concentration, asset-allocation trade-offs, downside risk and questions to consider. Do not prescribe a specific security, execute a trade, or claim personal suitability. Check arithmetic. Stay under 180 words.`:`Du bist FinTwin, ein warmer, aufmerksamer deutschsprachiger Finanzcoach in einem fortlaufenden vertraulichen Gespräch. Klinge wie ein kompetenter Mensch, niemals wie ein Bericht. Beginne mit der Antwort, die die Person wirklich braucht. Nutze zwei oder drei kurze natürliche Absätze, ohne Überschriften, Aufzählungen, Markdown, rohe Formeln oder Floskeln. Behalte den bisherigen Gesprächsverlauf im Blick. Der geprüfte Kontext enthält das angegebene Profil, die vollständige fiktive Haushaltsbilanz, Sparguthaben, Altersvorsorge, Immobilie, Hypothek, Depotpositionen, Kaufhistorie, verzögerte Marktpreise und Konzentrationskennzahlen. Trenne angegebene Werte, fiktive Datensätze und verzögerte Preise klar. Du darfst Diversifikation, Konzentration, Anlageklassen, Verlustrisiken und Abwägungen erklären. Empfiehl kein konkretes Wertpapier, führe keinen Handel aus und behaupte keine persönliche Eignung. Prüfe Zahlen. Höchstens 180 Wörter.`;
  const tool={type:"function",function:{name:"get_verified_financial_context",description:"Returns the complete verified account profile, household balance sheet, portfolio, delayed market reference data, scenarios and source IDs.",parameters:{type:"object",properties:{topic:{type:"string"}},required:["topic"],additionalProperties:false}}};
  const messages=[{role:"system",content:system},...conversation.slice(-10).map(i=>({role:i.role,content:i.text})),{role:"user",content:question}];
  const firstResponse=await groq("/chat/completions",env,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:env.GROQ_CHAT_MODEL||"openai/gpt-oss-120b",messages,tools:[tool],tool_choice:"required",temperature:.45,max_tokens:520})});const first=await firstResponse.json(),assistant=first.choices?.[0]?.message;if(!assistant?.tool_calls?.length)throw new Error("The model did not request verified context.");messages.push(assistant);for(const call of assistant.tool_calls)messages.push({role:"tool",tool_call_id:call.id,name:call.function.name,content:JSON.stringify(context)});
  const finalResponse=await groq("/chat/completions",env,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:env.GROQ_CHAT_MODEL||"openai/gpt-oss-120b",messages,temperature:.62,max_tokens:520})});const final=await finalResponse.json(),text=humanize(final.choices?.[0]?.message?.content?.trim()||"");if(!text)throw new Error("The model returned an empty answer.");return{display_response:text,claims:[{text,source_ids:sourceIds(context),confidence:"model_with_verified_context"}],policy_result:"allowed",mode:"groq_live",warnings:[language==="en"?"Educational AI interpretation using delayed reference prices; review important decisions with a qualified human.":"Einordnung durch KI mit verzögerten Referenzpreisen; wichtige Entscheidungen qualifiziert prüfen lassen."],tool_calls:[{name:"get_verified_financial_context",trace_id:first.id}]};
}
async function transcribe(request,env){const incoming=await request.formData(),audio=incoming.get("audio");if(!(audio instanceof File)||audio.size===0)return json({ok:false,error:"No recording received."},400);if(audio.size>15*1024*1024)return json({ok:false,error:"The recording is too large."},413);const form=new FormData();form.set("file",audio,audio.name||"question.webm");form.set("model","whisper-large-v3-turbo");form.set("language",incoming.get("language")==="en"?"en":"de");form.set("response_format","json");form.set("temperature","0");const response=await groq("/audio/transcriptions",env,{method:"POST",body:form}),result=await response.json();return json({ok:true,data:{transcript:result.text?.trim()||""}});}
async function synthesize(request,env){const body=await request.json(),language=body.language==="en"?"en":"de",input=String(body.text||"").trim().slice(0,200);if(!input)return json({ok:false,error:"No speech text received."},400);if(language!=="en")return json({ok:false,error:"Natural server voice is currently English-only.",fallback:"system_voice"},422);const response=await groq("/audio/speech",env,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model:env.GROQ_TTS_MODEL||"canopylabs/orpheus-v1-english",voice:env.GROQ_TTS_VOICE||"hannah",input,response_format:"wav"})});return new Response(response.body,{status:200,headers:{"content-type":"audio/wav","cache-control":"no-store"}});}

export default {async fetch(request,env){const url=new URL(request.url);try{
  if(url.pathname==="/health")return json({status:"ok",ai_available:Boolean(env.GROQ_API_KEY),ai_provider:env.GROQ_API_KEY?"groq":"demo",ai_model:env.GROQ_CHAT_MODEL||"openai/gpt-oss-120b",natural_voice:Boolean(env.GROQ_API_KEY),voice_model:env.GROQ_TTS_MODEL||"canopylabs/orpheus-v1-english",account_storage:Boolean(env.DB)});
  if(url.pathname==="/v1/account"){const viewer=viewerFromRequest(request);if(!viewer)return json({ok:false,error:"Sign in is required."},401);if(request.method==="GET")return json({ok:true,data:{profile:await readProfile(env,viewer.userId),viewer:{email:viewer.email,suggestedName:viewer.fullName}}});if(request.method==="POST"){const body=await request.json(),profile=await saveFullProfile(env,viewer,validatedFullProfile(body,viewer));return json({ok:true,data:{profile}},201);}if(request.method==="PATCH"){const body=await request.json(),profile=await patchProfile(env,viewer,body);return profile?json({ok:true,data:{profile}}):json({ok:false,error:"Complete onboarding first."},404);}}
  if(request.method==="GET"&&url.pathname==="/v1/portfolio"){const viewer=viewerFromRequest(request),profile=viewer&&env.DB?await readProfile(env,viewer.userId):null;return json({ok:true,data:await portfolioContext(profile)});}
  if(request.method==="GET"&&url.pathname==="/v1/copilot/history"){const viewer=viewerFromRequest(request);if(!viewer)return json({ok:false,error:"Sign in is required."},401);return json({ok:true,data:{messages:await loadConversation(env,viewer.userId,30),monitoring:"Conversation turns are retained for continuity, safety and quality monitoring."}});}
  if(request.method==="POST"&&url.pathname.endsWith("/copilot/turns")){const body=await request.json(),viewer=viewerFromRequest(request);let profile=null,conversation=[];if(viewer&&env.DB){profile=await readProfile(env,viewer.userId);conversation=await loadConversation(env,viewer.userId,10);}if(!profile&&body.profile)profile={name:String(body.profile.name||"FinTwin user").slice(0,80),netWorth:Number(body.profile.netWorth)||487320,expectations:String(body.profile.expectations||"Understand my finances").slice(0,500)};const question=String(body.question||"").trim().slice(0,4000);if(!question)return json({ok:false,error:"Please ask a question."},400);const data=await answerQuestion(question,env,body.language==="en"?"en":"de",profile,conversation),ids=data.claims.flatMap(c=>c.source_ids||[]);if(viewer&&env.DB){await saveTurn(env,viewer.userId,"user",question,[],body.mode==="voice"?"voice":"text");await saveTurn(env,viewer.userId,"assistant",data.display_response,ids,data.mode);}return json({ok:true,data,source_ids:ids});}
  if(request.method==="POST"&&url.pathname.endsWith("/voice/transcribe"))return await transcribe(request,env);if(request.method==="POST"&&url.pathname==="/v1/voice/synthesize")return await synthesize(request,env);
}catch(error){return json({ok:false,error:error instanceof Error?error.message:"Service unavailable"},502);}const response=await env.ASSETS.fetch(request);if(response.status!==404)return response;if(url.pathname.includes("."))return response;url.pathname="/index.html";return env.ASSETS.fetch(new Request(url,request));}};
