import { beforeEach, describe, expect, it, vi } from 'vitest';
import { client, testEnv } from './harness';
import { chatProvider } from '../src/providers';
import { normalizeFactValue, parseLocalizedNumber, retirement } from '@fintwin/engine';
import { reserve, usageSummary } from '../src/budget';
import { beginTurn, getHead, setFacts } from '../src/db';

let env:ReturnType<typeof testEnv>['env'], app:ReturnType<typeof client>;
beforeEach(async()=>{({env}=testEnv({FINTWIN_DEMO_PASSPHRASE:'synthetic-test-passphrase'}));app=client(env);await app.login();});
describe('C — conversational semantics',()=>{
  it('C01 first introduction captures all clear facts',async()=>{const result=await app.say('My name is Alex. I am 40 years old, earn 5000 net a month, spend 2500 a month and have 20000 in cash.');const s=await app.state();expect(s.profile?.name).toBe('Alex');expect(s.facts.age?.value).toBe(40);expect(s.facts.income_net_monthly?.value).toBe(5000);expect(s.facts.expenses_monthly?.value).toBe(2500);expect(s.facts.cash_liquid?.value).toBe(20000);expect(result.message?.text).not.toMatch(/how old|what comes in|what goes out/i);});
  it('C02 annual income without basis asks, never guesses net',async()=>{const r=await app.say('I earn 60000 a year.');expect((await app.state()).facts.income_net_monthly).toBeUndefined();expect(r.message?.text).toMatch(/gross or net/i);await app.say('net');expect((await app.state()).facts.income_net_monthly?.value).toBe(5000);});
  it('C03 annual net conversion retains provenance',async()=>{await app.say('My net income is 60000 euros per year.');const f=(await app.state()).facts.income_net_monthly!;expect(f.value).toBe(5000);expect(f.provenance).toMatchObject({period:'year',basis:'net',originalValue:60000});});
  it('C04 gross is not net',async()=>{await app.say('My gross salary is 60000 a year.');expect((await app.state()).facts.income_net_monthly).toBeUndefined();});
  it('C05 both cashflow facts in one sentence',async()=>{await app.say('Income is 5000 net monthly and spending is 2500 monthly.');expect((await app.state()).facts).toMatchObject({income_net_monthly:{value:5000},expenses_monthly:{value:2500}});});
  it('C06 negated value is not stored',async()=>{await app.say('No, spending is 2500, not 3500.');expect((await app.state()).facts.expenses_monthly?.value).toBe(2500);});
  it('C07 final self-correction wins',async()=>{await app.say('Actually 5500 — sorry, 5000 net monthly.');expect((await app.state()).facts.income_net_monthly?.value).toBe(5000);});
  it('C08–10 hypothetical, friend and partner do not overwrite income',async()=>{await app.say('Our household income is 5000 net monthly.');await app.say('What if I earned 7000?');await app.say('My friend earns 7000.');const r=await app.say('My partner earns 2000 as well.');expect((await app.state()).facts.income_net_monthly?.value).toBe(5000);expect(r.message?.text).toMatch(/combined|separate/i);});
  it('C11 skip and side questions preserve facts',async()=>{await app.say('My name is Alex. I earn 5000 net monthly.');await app.say('skip');await app.say('What is a mortgage?');expect((await app.state()).facts.income_net_monthly?.value).toBe(5000);});
  it('C12 removal is unknown, not zero',async()=>{await app.say('My income is 5000 net monthly.');await app.say('Forget my salary.');expect((await app.state()).facts.income_net_monthly).toBeUndefined();expect((await app.state()).picture.metrics.find(m=>m.key==='free_cashflow')?.value).toBeNull();});
  it('C13 German localized amounts',async()=>{await app.say('Ich verdiene 5.500,50 Euro netto im Monat und gebe 2.500 Euro aus.','de');expect((await app.state()).facts).toMatchObject({income_net_monthly:{value:5500.50},expenses_monthly:{value:2500}});});
});
describe('N/P — strict values and routing',()=>{
  it('N01 strict JSON, explicit locale parsing',()=>{for(const v of [null,'',' ','abc','5,500',NaN,Infinity])expect(normalizeFactValue('income_net_monthly',v)).toBeNull();expect(parseLocalizedNumber('5.500,50','de')).toBe(5500.5);expect(parseLocalizedNumber('5,500.50','en')).toBe(5500.5);expect(parseLocalizedNumber('5,500.50','de')).toBeNull();});
  it('N02 unknown versus zero pension',async()=>{await app.say("I don't know my pension.");expect((await app.state()).facts.expected_pension_monthly).toBeUndefined();await app.say('I expect no pension.');expect((await app.state()).facts.expected_pension_monthly?.value).toBe(0);expect(retirement({currentAssets:1000,monthlyContribution:100,years:10,targetSpendingMonthly:2000}).readinessRatio).toBeNull();});
  it('N03 currency/period unresolved',async()=>{await app.say('My income is 5000 dollars net monthly.');expect((await app.state()).facts.income_net_monthly).toBeUndefined();await app.say('My income is 5000 net.');expect((await app.state()).facts.income_net_monthly).toBeUndefined();});
  it('N04 invalid domain rejected',()=>{expect(()=>retirement({currentAssets:1000,monthlyContribution:1,years:-2})).toThrow();expect(normalizeFactValue('age',12)).toBeNull();});
  it('P01/P03 honest deterministic origin even with configured keys',async()=>{env.GROQ_API_KEY='synthetic-not-used';const fetchSpy=vi.spyOn(globalThis,'fetch');const r=await app.say('Call me Alex');expect(r.message?.meta?.origin).toBe('deterministic');expect(r.message?.meta?.provider).toBeUndefined();expect(fetchSpy).not.toHaveBeenCalled();fetchSpy.mockRestore();});
  it('P02/P04 provider precedence and explicit model',()=>{expect(chatProvider({GROQ_API_KEY:'test'})?.id).toBe('groq');const custom={LLM_BASE_URL:'https://custom.example/v1',LLM_API_KEY:'test',LLM_MODEL:'custom-model'};expect(chatProvider(custom)?.model).toBe('custom-model');expect(chatProvider({...custom,GROQ_API_KEY:'test'})?.id).toBe('custom.example');expect(chatProvider({...custom,LLM_MODEL:''})).toBeNull();});
});
describe('A/E — isolation and transactions',()=>{
  it('A01/A02 unsigned ids, wrong origin denied',async()=>{const other=client(env);expect((await other.call('/v1/state',{headers:{'x-fintwin-device':crypto.randomUUID(),'oai-authenticated-user-id':'forged'}})).status).toBe(401);expect((await app.call('/v1/facts',{method:'PATCH',headers:{origin:'https://attacker.example'},body:'{}'})).status).toBe(403);});
  it('A03 reservations survive and block after exhaustion',async()=>{env.FINTWIN_ALLOW_PAID='1';env.FINTWIN_SESSION_BUDGET_USD='1';await reserve(env,'synthetic-budget-user','chat','mock',0.75);await expect(reserve(env,'synthetic-budget-user','chat','mock',0.5)).rejects.toThrow();expect((await usageSummary(env,'synthetic-budget-user')).sessionUsed).toBe(0.75);});
  it('E03/E04 exact-once CAS prevents old generation overwriting newer facts',async()=>{const id='internal-synthetic';await beginTurn(env,id,'turn-one');const h=await getHead(env,id);const c={id:'mutation-one',expectedRevision:h.revision,epoch:h.epoch,turnId:'turn-one'};await setFacts(env,id,[{key:'cash_liquid',value:100}],'user',c);await setFacts(env,id,[{key:'cash_liquid',value:100}],'user',c);expect((await getHead(env,id)).revision).toBe(1);await beginTurn(env,id,'turn-two');await expect(setFacts(env,id,[{key:'cash_liquid',value:900}],'user',{...c,id:'old-late-result',expectedRevision:1})).rejects.toThrow();expect((await getHead(env,id)).revision).toBe(1);});
});
