import {describe,expect,it,vi,afterEach} from 'vitest';
import {client,testEnv} from './harness';
import {addNextStep,beginTurn,db,getHead,listNextSteps,resetUser,saveMessage,setFacts} from '../src/db';
import {reserve,usageSummary} from '../src/budget';
import {mortgage} from '@fintwin/engine';
afterEach(()=>vi.restoreAllMocks());
describe('release regressions — synthetic only',()=>{
  it('C08/C09 compound hypothetical and third-party clauses cannot leak into personal facts',async()=>{const {env}=testEnv({FINTWIN_DEMO_PASSPHRASE:'synthetic-test-passphrase'}),app=client(env);await app.login();await app.say('My friend earns 7000 net monthly and spends 2000 monthly.');await app.say('What if I earned 9000 net monthly and had 50000 in savings?');expect((await app.state()).facts).toEqual({});});
  it('E03 next-step retries have exactly one effective mutation',async()=>{const {env}=testEnv(),user='step-retry';await beginTurn(env,user,'turn-step');const h=await getHead(env,user),ctx={id:'same-tool-call',expectedRevision:h.revision,epoch:h.epoch,turnId:'turn-step'};const first=await addNextStep(env,user,'Bring the mortgage statement',ctx);const retry=await addNextStep(env,user,'Bring the mortgage statement',ctx);expect(retry.id).toBe(first.id);expect(await listNextSteps(env,user)).toHaveLength(1);expect((await getHead(env,user)).revision).toBe(1);});
  it('E04/S07 old message cannot repopulate a reset household',async()=>{const {env}=testEnv(),user='late-message';await beginTurn(env,user,'old-turn');const h=await getHead(env,user);await resetUser(env,user);await expect(saveMessage(env,user,{id:'late-id',role:'assistant',text:'Obsolete',cards:[],createdAt:new Date().toISOString()},{id:'message:late-id',expectedRevision:h.revision,epoch:h.epoch,turnId:'old-turn'})).rejects.toThrow();expect((await db(env).prepare('SELECT COUNT(*) AS n FROM conversation_turns').first<{n:number}>())?.n).toBe(0);});
  it('S07 edited synthetic household resets; real reported figures are preserved',async()=>{const {env}=testEnv({FINTWIN_DEMO_PASSPHRASE:'synthetic-test-passphrase'}),app=client(env);await app.login();await app.mutate('/v1/sample',{});await app.mutate('/v1/facts',{facts:[{key:'cash_liquid',value:1}]},'PATCH');expect((await app.mutate('/v1/sample',{confirmed:true})).status).toBe(200);expect((await app.state()).facts.cash_liquid?.value).toBe(61900);const own=client(env);await own.login();await own.say('My savings are 8000.');expect((await own.mutate('/v1/sample',{confirmed:true})).status).toBe(409);expect((await own.state()).facts.cash_liquid?.value).toBe(8000);});
  it('A03 reset cannot replenish reservations and aggregate cap covers reconnects',async()=>{const {env}=testEnv({FINTWIN_ALLOW_PAID:'1',FINTWIN_TOTAL_BUDGET_USD:'1'});await reserve(env,'session-one','chat','mock',.75);await resetUser(env,'session-one');expect((await usageSummary(env,'session-one')).sessionUsed).toBe(.75);await expect(reserve(env,'session-two','chat','mock',.5)).rejects.toThrow();});
  it('D01 contractual rounding residual does not invent another mortgage month',()=>{expect(mortgage(240000,2.15,240)).toMatchObject({payment:1231.24,payoffMonths:240,engineVersion:'mortgage-1.1.0'});});
  it('A02 oversized chunked JSON rejected before any provider call',async()=>{const {env}=testEnv(),app=client(env);const spy=vi.spyOn(globalThis,'fetch');const response=await app.call('/v1/chat',{method:'POST',body:JSON.stringify({text:'x'.repeat(65000)})});expect(response.status).toBe(413);expect(spy).not.toHaveBeenCalled();});
  it('Node batch rolls back all writes when a later statement fails',async()=>{const {env}=testEnv();await getHead(env,'rollback');await expect(db(env).batch([db(env).prepare('UPDATE household_heads SET revision=99 WHERE user_id=?').bind('rollback'),db(env).prepare('INSERT INTO table_that_does_not_exist VALUES (1)')])).rejects.toThrow();expect((await getHead(env,'rollback')).revision).toBe(0);});
  it('P02 actual custom invocation uses explicit model and shared intake; usage is recorded',async()=>{const {env}=testEnv({FINTWIN_DEMO_PASSPHRASE:'synthetic-test-passphrase',FINTWIN_ALLOW_PAID:'1',LLM_BASE_URL:'https://custom.example/v1',LLM_API_KEY:'mock-only',LLM_MODEL:'explicit-model',GROQ_API_KEY:'must-not-use'}),app=client(env);await app.login();const spy=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('data: {"choices":[{"delta":{"content":"Thanks Alex. What would you like to work toward?"},"finish_reason":"stop"}],"usage":{"prompt_tokens":20,"completion_tokens":10,"total_tokens":30}}\n\ndata: [DONE]\n\n'));const result=await app.say('My name is Alex. My income is 5000 net monthly.');expect(spy).toHaveBeenCalledOnce();const [url,init]=spy.mock.calls[0];expect(url).toBe('https://custom.example/v1/chat/completions');const payload=JSON.parse(String(init?.body));expect(payload.model).toBe('explicit-model');expect(payload.reasoning_format).toBeUndefined();expect(payload.messages[0].content).toContain('Source turn ID:');expect((await app.state()).facts.income_net_monthly?.value).toBe(5000);expect(result.message?.meta).toMatchObject({origin:'live',provider:'custom.example',model:'explicit-model'});expect((await db(env).prepare('SELECT tokens_json FROM usage_events').first<{tokens_json:string}>())?.tokens_json).toContain('30');});
  it('E01 partial live failure becomes a clean fallback without reapplying facts',async()=>{const {env}=testEnv({FINTWIN_DEMO_PASSPHRASE:'synthetic-test-passphrase',FINTWIN_ALLOW_PAID:'1',GROQ_API_KEY:'mock-only'}),app=client(env);await app.login();vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('data: {"choices":[{"delta":{"content":"This unfinished sentence must disappear before fallback text"}}]}\n\n'));const result=await app.say('My name is Alex. My income is 5000 net monthly.');expect(result.events.some(e=>e.type==='replace')).toBe(true);expect(result.message?.text).not.toContain('unfinished sentence');expect(result.message?.meta?.origin).toBe('fallback');expect((await app.state()).revision).toBe(1);});
});
