import {beforeEach,describe,expect,it} from 'vitest';
import {client,testEnv} from './harness';
import type {AppState,MeetingBrief,ScenarioSnapshot} from '@fintwin/contracts';
let env:ReturnType<typeof testEnv>['env'],app:ReturnType<typeof client>;
beforeEach(async()=>{env=testEnv({FINTWIN_DEMO_PASSPHRASE:'synthetic-test-passphrase'}).env;app=client(env);await app.login();await app.mutate('/v1/sample',{});});
const snapshot=async(kind:string,inputs:object)=>await app.mutate('/v1/scenarios',{kind,inputs}) as {status:number;data:{snapshot:ScenarioSnapshot;state:AppState}};
describe('S/B/D — authoritative shared outputs',()=>{
  it('S01 exact extra and baseline survive snapshot handoff',async()=>{const r=await snapshot('mortgage',{special_repayment_monthly:300});expect(r.status).toBe(200);expect(r.data.snapshot.inputs).toMatchObject({principal:240000,rate_pct:2.15,months:240,special_repayment_monthly:300,baseline_payment:1231.24});const said=await app.say('Explain this','en',{scenarioId:r.data.snapshot.id});expect(said.message?.text).toContain('€300');expect(said.message?.cards[0]).toMatchObject({type:'scenario',snapshot:{id:r.data.snapshot.id}});});
  it('S02/S03 retains pension, return, fees, inflation and withdrawal; zero overwrites',async()=>{const r=await snapshot('retirement',{pension_monthly:0,annual_return_pct:6,annual_fee_pct:0.7,inflation_pct:3,withdrawal_rate_pct:3.5});expect(r.data.snapshot.inputs).toMatchObject({pension_monthly:0,annual_return_pct:6,annual_fee_pct:0.7,inflation_pct:3,withdrawal_rate_pct:3.5});expect((await app.state()).facts.expected_pension_monthly?.value).toBe(2100);await app.mutate('/v1/facts',{facts:[{key:'expected_pension_monthly',value:0}]},'PATCH');expect((await app.state()).facts.expected_pension_monthly?.value).toBe(0);});
  it('S04 stale snapshots immutable and explicitly historical',async()=>{const s=(await snapshot('mortgage',{special_repayment_monthly:300})).data.snapshot;await app.mutate('/v1/facts',{facts:[{key:'mortgage_balance',value:200000}]},'PATCH');const read=await app.json(`/v1/scenarios/${s.id}`) as {data:ScenarioSnapshot};expect(read.data.stale).toBe(true);expect(read.data.inputs.principal).toBe(240000);const said=await app.say('Explain','en',{scenarioId:s.id});expect(said.message?.text).toMatch(/earlier household revision/);});
  it('S05 rejects forged browser results and malformed numeric overrides',async()=>{expect((await snapshot('mortgage',{result:{payment:1}})).status).toBe(422);for(const v of [null,'', '5.500,50',-1])expect((await snapshot('mortgage',{principal:v})).status).toBe(422);});
  it('S06 compares actual previous ids',async()=>{const a=(await snapshot('mortgage',{special_repayment_monthly:100})).data.snapshot,b=(await snapshot('mortgage',{special_repayment_monthly:300})).data.snapshot;expect(b.previousId).toBe(a.id);const said=await app.say('Compare with the previous scenario','en',{scenarioId:b.id});expect(said.message?.cards.filter(c=>c.type==='scenario').map(c=>c.snapshot.id)).toEqual([b.id,a.id]);});
  it('S07/D02 reset preserves immutable history but changes epoch and clears active selection',async()=>{const s=(await snapshot('mortgage',{})).data.snapshot;const a=await app.state();await app.mutate('/v1/sample',{confirmed:true});const b=await app.state();expect(b.epoch).toBeGreaterThan(a.epoch);expect(b.scenarios).toHaveLength(0);const read=await app.json(`/v1/scenarios/${s.id}`) as {data:ScenarioSnapshot};expect(read.data.stale).toBe(true);expect(Object.fromEntries(Object.entries(a.facts).map(([k,f])=>[k,f!.value]))).toEqual(Object.fromEntries(Object.entries(b.facts).map(([k,f])=>[k,f!.value])));});
  it('D01 reconciled baseline does not invent savings or double housing',async()=>{const s=(await snapshot('mortgage',{})).data.snapshot;expect(s.delta.payment).toBe(0);expect(s.delta.interest).toBe(0);expect(s.delta.remaining_after_saving).toBe(188.76);});
  it('B01/B04 deterministic brief references current facts and scenario',async()=>{const s=(await snapshot('mortgage',{special_repayment_monthly:300})).data.snapshot;const first=await app.json('/v1/brief',{method:'POST',body:JSON.stringify({language:'en',scenarioId:s.id})}) as {data:MeetingBrief};expect(first.data.fields.every(f=>f.source.startsWith('fact:'))).toBe(true);expect(first.data.scenarioFields.every(f=>f.source.startsWith(`scenario:${s.id}:`))).toBe(true);await app.mutate('/v1/facts',{facts:[{key:'cash_liquid',value:100}]},'PATCH');const next=await app.json('/v1/brief',{method:'POST',body:'{"language":"en"}'}) as {data:MeetingBrief};expect(next.data.revision).toBeGreaterThan(first.data.revision);expect(next.data.fields.find(f=>f.source.startsWith('fact:cash_liquid'))?.value).toBe('100 EUR');});
  it('A01 another session cannot read or export a scenario',async()=>{const s=(await snapshot('mortgage',{})).data.snapshot,other=client(env);await other.login();expect((await other.call(`/v1/scenarios/${s.id}`)).status).toBe(404);expect((await other.call('/v1/brief',{method:'POST',body:JSON.stringify({language:'en',scenarioId:s.id})})).status).toBe(404);});
});
