"use client";
import {useCallback,useEffect,useState} from 'react';
import {FileText,Printer,RefreshCw} from 'lucide-react';
import type {AppState,Lang,MeetingBrief} from '@fintwin/contracts';
import {api} from '../lib/api';
import {assumptionLabel,scenarioLabel,scenarioName} from '../lib/scenarios';
export function BriefView({state,lang,scenarioId,onEdit}:{state:AppState;lang:Lang;scenarioId?:string;onEdit():void}){
  const [brief,setBrief]=useState<MeetingBrief|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sources,setSources]=useState(false),[historical,setHistorical]=useState(false);
  const de=lang==='de';
  const refresh=useCallback(async()=>{setBusy(true);setError('');try{setBrief(await api.brief(lang,scenarioId));setHistorical(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}},[lang,scenarioId]);
  useEffect(()=>{void refresh();},[refresh]);
  const stale=Boolean(brief&&(brief.revision!==state.revision||brief.epoch!==state.epoch||brief.scenario?.stale));
  return <div className="page brief-page"><div className="page-head no-print"><div><span className="eyebrow">{de?'Aus Ihren Angaben. Für Ihr Gespräch.':'From your facts. For your conversation.'}</span><h1>{de?'Gut vorbereitet ins Gespräch':'Arrive with a clearer picture'}</h1><p className="lead">{de?'Prüfen Sie den Überblick und korrigieren Sie offene Punkte. Drucken speichert oder sendet nichts an eine andere Person.':'Review this overview and correct anything missing. Printing does not send it to anyone.'}</p></div><div className="brief-actions"><button className="btn" onClick={onEdit}>{de?'Angaben bearbeiten':'Edit facts'}</button><button className="btn" disabled={busy} onClick={()=>void refresh()}><RefreshCw/>{de?'Aktualisieren':'Refresh'}</button><button className="btn primary" disabled={!brief||busy||(stale&&!historical)} onClick={()=>window.print()}><Printer/>{de?'Drucken / PDF':'Print / save PDF'}</button></div></div>
    {error&&<p role="alert" className="error-line">{error}</p>}
    {stale&&<div className="banner no-print"><span>{de?'Dieser Überblick enthält eine frühere Haushaltsversion. Aktualisieren Sie ihn; veraltete Szenarien müssen in der Planung neu berechnet werden.':'This brief includes an earlier household revision. Refresh it; stale scenarios must be recalculated in Plan.'}</span><label><input type="checkbox" checked={historical} onChange={e=>setHistorical(e.target.checked)}/>{de?'Bewusst als historischen Stand exportieren':'Explicitly export as a historical snapshot'}</label></div>}
    {brief&&<><button className="btn sm ghost no-print" onClick={()=>setSources(!sources)}>{de?'Quellen anzeigen':'View sources'}</button><article className="meeting-brief" aria-label={brief.title}><header className="brief-title"><span className="mark"><FileText/></span><div><h2>{brief.title}</h2><p>FinTwin · {new Intl.DateTimeFormat(de?'de-DE':'en-GB',{dateStyle:'medium'}).format(new Date(brief.createdAt))} · {de?'Version':'Revision'} {brief.revision}</p></div></header>
      {brief.synthetic&&<div className="brief-sample">{de?'SYNTHETISCHER BEISPIELHAUSHALT · KEINE ECHTEN KUNDENDATEN':'SYNTHETIC SAMPLE HOUSEHOLD · NOT REAL CLIENT DATA'}</div>}
      {stale&&<p className="brief-sample">{de?'Historischer Stand – nicht das aktuelle Haushaltsbild':'Historical snapshot — not the current household picture'}</p>}
      <section><h3>{de?'Was mir wichtig ist':'What matters to me'}</h3><p>{brief.synthetic&&brief.objective==='Retire at 63 with the house paid off'&&de?'Mit 63 in Rente gehen und das Haus bis dahin abbezahlt haben.':brief.objective}</p></section>
      <section><h3>{de?'Erfasste Angaben':'Recorded facts'}</h3><div className="brief-facts">{brief.fields.map(field=><div key={field.source}><span>{field.label}</span><strong className="num">{field.value}</strong>{sources&&<small className="source-detail no-print">{field.meaning} · {field.source}</small>}</div>)}</div><p className="note">{de?'Schätzwerte aus dem Gespräch, sofern nicht als Beispiel gekennzeichnet; keine externe Verifizierung.':'Estimates reported in conversation unless labelled sample; not externally verified.'}</p></section>
      {brief.scenario&&<section><h3>{de?'Besprochene Alternative':'Selected alternative'} · {scenarioName(brief.scenario.kind,lang)}</h3><div className="brief-facts">{brief.scenarioFields.map(field=><div key={field.source}><span>{field.label.startsWith('Δ ')?'Δ ':''}{scenarioLabel(field.label,lang)}</span><strong className="num">{field.value}</strong>{sources&&<small className="source-detail no-print">{field.source} · {field.meaning}</small>}</div>)}</div><p className="note">{de?'Unveränderlicher Modellstand, kein Angebot.':'Immutable model snapshot, not an offer.'} {brief.scenario.engineVersion} · {brief.scenario.asOf.slice(0,10)}</p></section>}
      {brief.assumptions.length>0&&<section><h3>{de?'Annahmen und Grenzen':'Assumptions and limits'}</h3><p className="brief-assumptions">{brief.assumptions.map(k=>assumptionLabel(k,lang)).join(' ')}</p></section>}
      <div className="brief-columns"><section><h3>{de?'Noch zu klären':'Still to clarify'}</h3>{brief.unknowns.length?<ul>{brief.unknowns.map(q=><li key={q}>{q}</li>)}</ul>:<p>{de?'Keine weiteren Grundangaben offen. Unterlagen prüfen.':'No further basic facts missing. Review supporting documents.'}</p>}</section><section><h3>{de?'Mögliche Unterlagen':'Documents that may help'}</h3><ul>{brief.documents.map(d=><li key={d}>{d}</li>)}</ul></section></div>
      <section><h3>{de?'Fragen und nächste Schritte':'Questions and next steps'}</h3><ul>{[...brief.questions.slice(0,2),...brief.nextSteps].map((q,i)=><li key={i}>{q}</li>)}</ul></section>
      <footer>{de?'Unabhängige Vorbereitung für ein Beratungsgespräch. Keine Produktempfehlung, Eignungsprüfung oder regulierte Beratungsdokumentation. Keine Verbindung zu DVAG.':'Independent meeting preparation. Not a product recommendation, suitability assessment or regulated advice record. No DVAG affiliation.'}</footer>
    </article></>}
  </div>;
}
