"use client";
import {useEffect,useState} from 'react';
import type {AppState,Lang} from '@fintwin/contracts';
import {api} from '../lib/api';
export function Preflight({state,lang,onClose}:{state:AppState;lang:Lang;onClose():void}){
  const [data,setData]=useState<Awaited<ReturnType<typeof api.preflight>>|null>(null),[error,setError]=useState(''),[mic,setMic]=useState('not checked');const de=lang==='de';
  useEffect(()=>{void api.preflight().then(setData).catch(e=>setError(e.message));void navigator.permissions?.query({name:'microphone' as PermissionName}).then(p=>setMic(p.state)).catch(()=>setMic('Browser permission prompt required'));},[]);
  return <div className="page"><div className="page-head"><div><h1>{de?'Vorführungscheck':'Presenter preflight'}</h1><p className="lead">{de?'Nur für die Vorbereitung. Konfiguration ist kein bestandener Audiotest.':'For preparation only. Configuration is not a passed audio test.'}</p></div><button className="btn" onClick={onClose}>{de?'Zurück':'Back'}</button></div>{error&&<p role="alert">{error}</p>}{data&&<section className="panel"><dl className="assumption-grid"><div><dt>Backend</dt><dd>{de?'Erreichbar':'Reachable'}</dd></div><div><dt>{de?'Textmodell':'Text model'}</dt><dd>{data.ai.live?`${data.ai.provider} · ${data.ai.model}`:(de?'Deterministischer Modus':'Deterministic mode')}</dd></div><div><dt>{de?'Sprachverbindung':'Voice connection'}</dt><dd>{data.ai.realtime.available?'Realtime':data.ai.realtime.mode!=='text'&&data.ai.speechIn.provider!=='none'?(de?'Aufnahme → Transkription → Antwort':'Recording → transcription → reply'):data.ai.realtime.reason}</dd></div><div><dt>{de?'Stimme / Sprache':'Voice / language'}</dt><dd>{data.ai.realtime.available?data.ai.realtime.voice:data.ai.voice?data.ai.speechOut.voice:'—'} / {lang.toUpperCase()}</dd></div><div><dt>{de?'Mikrofonberechtigung':'Microphone permission'}</dt><dd>{mic}</dd></div><div><dt>{de?'Letzter Live-Smoke-Test':'Last live smoke test'}</dt><dd>{data.smoke.at??(de?'Nicht ausgeführt':'Not run')}</dd></div><div><dt>{de?'Beispielversion':'Sample version'}</dt><dd>{state.sampleVersion??'—'}</dd></div><div><dt>{de?'Verbleibende Nutzung (Schätzung)':'Remaining usage (estimate)'}</dt><dd>USD {data.usage.remaining.toFixed(2)}</dd></div></dl><p className="note">{data.usage.basis}</p><p>{de?'Offline funktionieren Text, Rechner und Gesprächsüberblick. Live-Modell und Stimme benötigen Internet.':'Offline text, calculators and meeting briefs work without providers. Live models and voice require internet.'}</p></section>}</div>;
}
