"use client";
import {ArrowUpRight,Check,ChevronRight,Landmark,MessageSquare,Sparkles,TrendingUp} from 'lucide-react';
import type {AppState,Lang} from '@fintwin/contracts';
import {FACT_BY_KEY} from '@fintwin/engine';
import {factDisplay,metricValue,money} from '../lib/format';
import {SpendingChart} from './Bank';

export function Welcome({lang,onStart,onSample}:{lang:Lang;onStart:()=>void;onSample:()=>void}){
  const de=lang==='de';
  return <section className="opening welcome-grid"><div className="welcome-copy"><span className="eyebrow"><span className="eyebrow-line"/>{de?'Ihr finanzielles zweites Ich':'Your financial second self'}</span><h1>{de?<>Ihr Geld.<br/><em>Das ganze Bild.</em></>:<>Your money.<br/><em>In full view.</em></>}</h1><p>{de?'Sprechen Sie einfach. FinTwin merkt sich Ihre Angaben, verbindet die Zahlen und macht Möglichkeiten sichtbar.':'Just talk. FinTwin remembers the details, connects the numbers, and turns your questions into a clearer picture.'}</p><div className="opening-actions"><button className="btn primary" onClick={onSample}>{de?'Beispielhaushalt erkunden':'Explore a sample household'}<ArrowUpRight/></button><button className="btn ghost" onClick={onStart}>{de?'Gespräch beginnen':'Start a conversation'}</button></div><p className="welcome-note"><Check/>{de?'Ohne Bankzugang. Mit klar gekennzeichneten Demo-Daten.':'No bank credentials. Clearly labelled demo data.'}</p></div>
    <div className="welcome-demo"><div className="welcome-demo-head"><span className="mark"><Sparkles/></span><span>FinTwin <small>{de?'Ein Gespräch. Ein Überblick.':'One conversation. One picture.'}</small></span><span className="chip">DEMO</span></div><div className="welcome-demo-title">{de?'Weniger Eingaben.':'Less form-filling.'}<br/><span>{de?'Mehr Aha-Momente.':'More “now I see”.'}</span></div><div className="welcome-steps">{(de?[[MessageSquare,'Erzählen, wie Sie sprechen','Alter & Ziel · Einnahmen & Ausgaben · Vermögen'],[Landmark,'Verstehen, wohin Ihr Geld fließt','Sechs Monate Buchungen, Kategorien und Trends'],[TrendingUp,'Möglichkeiten sichtbar machen','Hypothek und Ruhestand im direkten Vergleich']]:[[MessageSquare,'Tell it in your own words','Age & goal · income & spending · assets'],[Landmark,'See where the money goes','Six months of transactions, categories and trends'],[TrendingUp,'Make the possibilities tangible','Compare mortgage and retirement scenarios']]).map(([Icon,title,body],i)=>{const Glyph=Icon as typeof Sparkles;return <div key={i}><span className="welcome-step-icon"><Glyph/></span><div><strong>{String(title)}</strong><small>{String(body)}</small></div></div>;})}</div><div className="welcome-demo-footer"><span>01 — 03</span><span>{de?'Drei kurze Antworten zum Start':'Three short replies to get started'}</span></div></div>
  </section>;
}

export function WorkspaceOverview({state,lang,onPicture}:{state:AppState;lang:Lang;onPicture:()=>void}){
  const de=lang==='de',find=(key:string)=>state.picture.metrics.find(m=>m.key===key),wealth=find('net_worth');
  return <section className="workspace-overview" aria-label={de?'Finanzüberblick':'Financial overview'}>
    <button className="wealth-hero" onClick={onPicture}><div><span className="eyebrow">{state.profile?.name?(de?`${state.profile.name}s Überblick`:`${state.profile.name}’s financial picture`):de?'Ihr finanzieller Überblick':'Your financial picture'}</span><span className="wealth-label">{wealth?.label[lang]??(de?'Erfasstes Nettovermögen':'Recorded net worth')}</span><strong className="num">{wealth?.value!=null?money(wealth.value,lang):'—'}</strong><small>{state.profile?.sampleLoaded?(de?'Synthetischer Haushalt · Stand 4. September 2026':'Synthetic household · as of 4 September 2026'):de?'Wächst mit Ihren Angaben':'Built from what you tell me'}</small></div><ArrowUpRight className="wealth-arrow"/></button>
    {['free_cashflow','runway'].map(key=>{const metric=find(key);return <button className="overview-tile" key={key} onClick={onPicture}><span className="overview-symbol">{key==='free_cashflow'?<TrendingUp/>:<Landmark/>}</span><small>{metric?.label[lang]}</small><strong className="num">{metric?metricValue(metric.value,metric.unit,lang):'—'}</strong><span>{key==='free_cashflow'?(de?'Vor vereinbarten Sparraten':'Before committed saving'):(de?'Auf Basis Ihrer Monatsausgaben':'Based on monthly spending')}</span></button>;})}
  </section>;
}

export function InsightRail({state,lang,send,onBank,onPicture,onSample}:{state:AppState;lang:Lang;send:(text:string)=>void;onBank:()=>void;onPicture:()=>void;onSample:()=>void}){
  const de=lang==='de',known=Object.values(state.facts).filter(Boolean).sort((a,b)=>b!.updatedAt.localeCompare(a!.updatedAt));
  return <aside className="rail intelligence-rail" aria-label={de?'Einblicke & Gedächtnis':'Insights and memory'}>
    <section className="panel bank-connection"><div className="panel-title"><span className="rail-icon"><Landmark/></span><div><h3>{de?'Verbundenes Demo-Konto':'Connected demo account'}</h3><small>{state.bank?'FinTwin Demo Bank':de?'Noch kein Konto':'No account connected'}</small></div></div>{state.bank?<><div className="connection-balance"><strong className="num">{money(state.bank.balanceCents/100,lang)}</strong><span>{state.bank.account}</span></div><SpendingChart months={state.bank.months} lang={lang} compact onSelect={onBank}/><button className="rail-link" onClick={onBank}>{de?'Buchungen erkunden':'Explore transactions'}<ChevronRight/></button><p className="note">{de?'Synthetisch · März–August 2026':'Synthetic · March–August 2026'}</p></>:<><p>{de?'Entdecken Sie Ausgabentrends mit sechs Monaten fiktiver Bankdaten.':'Explore spending trends with six months of fictional bank data.'}</p><button className="btn ghost" onClick={onSample}>{de?'Demo laden':'Load the demo'}<ArrowUpRight/></button></>}</section>
    {state.picture.insights.length>0&&<section className="panel priority-panel"><h3><Sparkles/>{de?'Ein genauerer Blick lohnt sich':'Worth a closer look'}</h3>{state.picture.insights.slice(0,2).map((insight,i)=><button className="priority-item" onClick={()=>send(insight.ask[lang])} key={insight.id}><span className="priority-number">0{i+1}</span><span><strong>{insight.title[lang]}</strong><small>{insight.body[lang]}</small></span><ArrowUpRight/></button>)}</section>}
    <section className="panel memory-panel"><h3>{de?'Ihr Finanzgedächtnis':'Your financial memory'}<span>{known.length}</span></h3>{state.profile?.name&&<div className="memory-fact"><span>{de?'Name':'Name'}</span><strong>{state.profile.name}</strong><Check/></div>}{known.slice(0,4).map(f=><div className="memory-fact" key={f!.key}><span>{FACT_BY_KEY[f!.key].label[lang]}</span><strong className="num">{factDisplay(f!.key,f!.value,lang)}</strong><Check/></div>)}{known.length===0&&<p>{de?'Ihre Angaben erscheinen hier, sobald Sie sie teilen. Nichts wird hinzugedacht.':'Details appear here as you share them. Nothing is filled in by guesswork.'}</p>}<button className="rail-link" onClick={onPicture}>{de?'Alle Angaben prüfen & bearbeiten':'Review & edit every fact'}<ChevronRight/></button></section>
  </aside>;
}
